version: '2'

services:

  app:
    container_name: app
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache

  nginx:
    container_name: nginx
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "81:80"
