<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV4q6js6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV4q6js6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV4q6js6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV4q6js6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV4q6js6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'V4q6js6',
    'container.build_id' => '9f8e46be',
    'container.build_time' => 1523598166,
));
