<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3d1sgm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3d1sgm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR3d1sgm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR3d1sgm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR3d1sgm\appDevDebugProjectContainer(array(
    'container.build_hash' => 'R3d1sgm',
    'container.build_id' => '1c41fa3a',
    'container.build_time' => 1521795079,
));
