<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8dz4ks0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8dz4ks0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8dz4ks0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8dz4ks0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8dz4ks0\appDevDebugProjectContainer(array(
    'container.build_hash' => '8dz4ks0',
    'container.build_id' => '425b4595',
    'container.build_time' => 1521803899,
));
