<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLnmc2hw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLnmc2hw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLnmc2hw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLnmc2hw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLnmc2hw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lnmc2hw',
    'container.build_id' => '8bdf260f',
    'container.build_time' => 1521729825,
));
